### ISSUE TITLE
Images can't be pulled from hub.docker.com

### ISSUE THREAD

**Issue by sbidy** [SecurityRAT/SecurityRATv2-dockercompose#1]
Can you please post the container to the docker hub repo to avoid building the container locally?

**Comment by rylyade1** [comment]
Hi @sbidy 

the SecurityRATv2 is still under development. There is no release for that yet. Once this is available, the respective docker images will be uploaded to Dockerhub. Check out https://github.com/SecurityRAT/SecurityRAT-dockercompose (link to docker-compose for SecurityRATv1).
